# -*- coding: utf-8 -*-
"""Figure 2: Two-Dimensional Threshold-Based Promotion Policy Map.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1srvbS2B6UJQp1pD9c3imGRzedxXUpess
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap


delta_star = 17.23
theta_star = 0.0426


delta = np.linspace(0, 25, 500)
theta = np.linspace(0, 0.12, 500)

D, T = np.meshgrid(delta, theta)



policy = np.zeros_like(D)


policy[(D < delta_star) & (T >= theta_star)] = 1


policy[D >= delta_star] = 2


fig, ax = plt.subplots(figsize=(10, 6))

cmap = ListedColormap([
    "#4F81BD",  # Discount
    "#9BBB59",  # Bundle
    "#C0504D"   # BOGO
])

ax.contourf(
    D,
    T * 100,
    policy,
    levels=[-0.5, 0.5, 1.5, 2.5],
    cmap=cmap,
    alpha=0.8
)



ax.axvline(
    delta_star,
    color="black",
    linestyle="--",
    linewidth=2,
    label= r"$\delta^*_{theoretical}=17.23$"
)

ax.axhline(
    theta_star * 100,
    color="black",
    linestyle=":",
    linewidth=2,
    label=r"$\tilde{\theta}=4.26\%$"
)



ax.text(
    3,
    2,
    "Discount Preferred Region",
    fontsize=14,
    fontweight="bold",
    color="white"
)

ax.text(
    3,
    8,
    "Bundle pricing Preferred Region",
    fontsize=14,
    fontweight="bold",
    color="white"
)

ax.text(
    19,
    6,
    "BOGO \nPreferred Region",
    fontsize=14,
    fontweight="bold",
    color="white"
)



ax.set_xlabel(
    r"Physical Deterioration Coefficient ($\delta$)",
    fontsize=12
)

ax.set_ylabel(
    r"Behavioural Demand Expansion ($\theta_{Bundle}$)",
    fontsize=12
)


ax.legend()
ax.grid(alpha=0.2)

plt.tight_layout()
plt.show()