# -*- coding: utf-8 -*-
"""Figure 8: Strategy Performance under Behavioural Demand Expansion (δ= 2.0).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wd5eOtUt_6ePdf1YXHQpz2XgU0TfdI0q
"""

import matplotlib.pyplot as plt
import numpy as np

theta_range = np.linspace(0.0, 0.10, 101)

z_discount_val = 1001.00
z_discount = np.full_like(theta_range, z_discount_val)

z_bundle_baseline = 1541.10
theta_tilde_val = 0.0426

slope = (z_bundle_baseline - z_discount_val) / (0.10 - theta_tilde_val)
z_bundle = z_discount_val + slope * (theta_range - theta_tilde_val)

plt.figure(figsize=(11, 6.5))

plt.axvline(
    x=theta_tilde_val * 100, color='black', linestyle=':', linewidth=2.0, zorder=2
)

plt.plot(
    theta_range * 100,
    z_discount,
    color='blue',
    linestyle='--',
    linewidth=2.2,
    label='Discount ',
    zorder=3,
)
plt.plot(
    theta_range * 100,
    z_bundle,
    color='green',
    linestyle='-',
    linewidth=2.5,
    label='Bundle Pricing',
    zorder=4,
)

plt.scatter(
    [theta_tilde_val * 100], [z_discount_val], color='black', s=90, zorder=10
)

plt.scatter([10.0], [z_bundle_baseline], color='green', s=110, zorder=10)

plt.text(
    9.8,
    z_bundle_baseline + 25,
    rf'Baseline Setting ($\theta_{{\mathrm{{Bundle}}}} = 10\%, Z_{{det}} = {z_bundle_baseline:.2f}$)',
    fontsize=9.5,
    fontweight='bold',
    color='black',
    ha='right',
    va='bottom',
)

plt.text(
    theta_tilde_val * 100 + 0.8,
    1050.0,
    rf'$\tilde{{\theta}} = {theta_tilde_val*100:.2f}\%$',
    fontsize=9.5,
    fontweight='bold',
    color='black',
    ha='left',
    va='center',
)

plt.text(
    9,
    1250.0,
    'Bundle Preferred Zone',
    fontsize=10.5,
    fontweight='bold',
    color='darkgreen',
    ha='center',
    va='center',
)

plt.text(
    2.4,
    1150.0,
    'Discount Preferred Zone',
    fontsize=10.5,
    fontweight='bold',
    color='blue',
    ha='center',
    va='center',
)

plt.xlabel(
    r'Consumer Bundle Demand Expansion Factor ($\theta_{\mathrm{Bundle}}$ in %)',
    fontsize=10,
)

plt.ylabel('Deterministic Socially Adjusted Value Z', fontsize=10)
plt.xlim(-0.5, 11.0)
plt.ylim(800, 1700)
plt.legend(loc='lower right', fontsize=9.5, framealpha=0.95)
plt.grid(True, linestyle=':', alpha=0.6)
plt.tight_layout()

plt.show()