# -*- coding: utf-8 -*-
"""Table4: Deterministic Strategy Performance under Different Perishability Levels.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZAyUZJU6b0uy3sGYeeSViwVyMrwjv1NK
"""

import pandas as pd


a = 200.0
b = 1.0
t = 3.0

Q = 200.0

C = 40.0
C_w = 2.0
lambda_pen = 2.0

theta_disc = 0.00
theta_bund = 0.10
theta_bogo = 0.20

P_DISC = 95.0
P_BUND = 75.0
P_BOGO = 50.0


def obj(P, D):
    return P * D - C * Q - (C_w + lambda_pen) * (Q - D)


def compute_table4():

    results = []

    for delta, label in [
        (2.0, "Low Perishability"),
        (18.0, "High Perishability")
    ]:


        D_disc = (1 + theta_disc) * (
            a - b * P_DISC - delta * t
        )

        Z_disc = obj(P_DISC, D_disc)

        results.append({
            "Perishability": label,
            "Strategy": "Discount",
            "Parameter": "d = 0.05",
            "Demand D_s": round(D_disc, 1),
            "Objective Z_s": round(Z_disc, 2)
        })


        D_bund = (1 + theta_bund) * (
            a - b * P_BUND - delta * t
        )

        Z_bund = obj(P_BUND, D_bund)

        results.append({
            "Perishability": label,
            "Strategy": "Bundle",
            "Parameter": "α = 0.75",
            "Demand D_s": round(D_bund, 1),
            "Objective Z_s": round(Z_bund, 2)
        })


        D_bogo = (1 + theta_bogo) * (
            a - b * P_BOGO - delta * t
        )

        Z_bogo = obj(P_BOGO, D_bogo)

        results.append({
            "Perishability": label,
            "Strategy": "BOGO",
            "Parameter": "Fixed",
            "Demand D_s": round(D_bogo, 1),
            "Objective Z_s": round(Z_bogo, 2)
        })

    return pd.DataFrame(results)


if __name__ == "__main__":

    df = compute_table4()

    print("\n=== Table 4 Deterministic Strategy Performance ===\n")
    print(df.to_string(index=False))