# -*- coding: utf-8 -*-
"""Table A3: Monte Carlo Replication Stability Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15oddSvpMZCKsz-9lsoFvjmI327Puw6ZI
"""

# -*- coding: utf-8 -*-

import numpy as np
import pandas as pd

# =====================================================
# Baseline Parameters (same as Table 3)
# =====================================================

a = 200.0
b = 1.0
t = 3.0

P_orig = 100.0
d = 0.05
alpha = 0.75

C = 40.0
C_w = 2.0
lambda_pen = 2.0

Q = 200.0

theta_disc = 0.00
theta_bund = 0.10
theta_bogo = 0.20

delta = 2.0
sigma = 20.0

# =====================================================
# Prices
# =====================================================

P_disc = P_orig * (1 - d)
P_bund = P_orig * alpha
P_bogo = P_orig * 0.50

# =====================================================
# Create ONE common random sample pool
# =====================================================

np.random.seed(42)

MAX_N = 20000

epsilon_pool = np.random.normal(
    0,
    sigma,
    MAX_N
)

# =====================================================
# Strategy evaluation
# =====================================================

def evaluate_strategy(P, theta, N):

    epsilon = epsilon_pool[:N]

    D = (1 + theta) * (
        a - b * P - delta * t
    )

    sales = np.minimum(
        D + epsilon,
        Q
    )

    waste = np.maximum(
        0.0,
        Q - sales
    )

    Z = (
        P * sales
        - C * Q
        - (C_w + lambda_pen) * waste
    )

    return np.mean(Z)

# =====================================================
# Evaluate all strategies
# =====================================================

def evaluate_all(N):

    return {

        "Discount":
        evaluate_strategy(
            P_disc,
            theta_disc,
            N
        ),

        "Bundle":
        evaluate_strategy(
            P_bund,
            theta_bund,
            N
        ),

        "BOGO":
        evaluate_strategy(
            P_bogo,
            theta_bogo,
            N
        )
    }

# =====================================================
# Relative deviation
# =====================================================

def max_relative_deviation(result, benchmark):

    values = []

    for strategy in benchmark:

        dev = abs(
            result[strategy]
            - benchmark[strategy]
        ) / abs(
            benchmark[strategy]
        )

        values.append(dev)

    return max(values)

# =====================================================
# Status label
# =====================================================

def status_label(dev):

    pct = dev * 100

    if pct > 3:
        return "Unconverged"

    elif pct > 0.5:
        return "Provisionally Converged"

    elif pct > 0.05:
        return "Numerically Stable"

    elif pct > 0.01:
        return "Baseline Simulation Standard"

    else:
        return "Benchmark Reference Solution"

# =====================================================
# Build Table A3
# =====================================================

def build_table_a3():

    N_list = [
        100,
        1000,
        5000,
        10000,
        20000
    ]

    benchmark = evaluate_all(20000)

    rows = []

    for N in N_list:

        result = evaluate_all(N)

        dev = max_relative_deviation(
            result,
            benchmark
        )

        rows.append({

            "Replications (N)":
            f"{N:,}",

            "Discount E[Z]":
            round(result["Discount"], 2),

            "Bundle E[Z]":
            round(result["Bundle"], 2),

            "BOGO E[Z]":
            round(result["BOGO"], 2),

            "Relative Deviation":
            f"{dev*100:.2f}%",

            "Convergence Status":
            status_label(dev)

        })

    return pd.DataFrame(rows)

# =====================================================
# Main
# =====================================================

if __name__ == "__main__":

    df = build_table_a3()

    print("\n=== Table A3: Monte Carlo Convergence Diagnostic ===\n")

    print(df.to_string(index=False))