# -*- coding: utf-8 -*-
"""Table3: Baseline Strategy Performance under Stochastic Demand.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r92Ccg1vaxPlsKZRdGRjXO7eEvQjOBPy
"""

import numpy as np
import pandas as pd


a = 200.0
b = 1.0
t = 3.0
P_orig = 100.0
d = 0.05
alpha = 0.75

C = 40.0
C_w = 2.0
lambda_pen = 2.0
Q = 200.0

theta_disc = 0.00
theta_bund = 0.10
theta_bogo = 0.20

delta = 2.0
sigma = 20.0
N_sim = 10000

np.random.seed(42)
epsilon = np.random.normal(0, sigma, N_sim)


P_disc = P_orig * (1 - d)
D_disc = (1 + theta_disc) * (a - b * P_disc - delta * t)
sales_disc = np.minimum(D_disc + epsilon, Q)
waste_disc = np.maximum(0.0, Q - sales_disc)
Z_disc = P_disc * sales_disc - C * Q - (C_w + lambda_pen) * waste_disc


P_bund = P_orig * alpha
D_bund = (1 + theta_bund) * (a - b * P_bund - delta * t)
sales_bund = np.minimum(D_bund + epsilon, Q)
waste_bund = np.maximum(0.0, Q - sales_bund)
Z_bund = P_bund * sales_bund - C * Q - (C_w + lambda_pen) * waste_bund


P_bogo = P_orig * 0.50
D_bogo = (1 + theta_bogo) * (a - b * P_bogo - delta * t)
sales_bogo = np.minimum(D_bogo + epsilon, Q)
waste_bogo = np.maximum(0.0, Q - sales_bogo)
Z_bogo = P_bogo * sales_bogo - C * Q - (C_w + lambda_pen) * waste_bogo


df_t2 = pd.DataFrame([
    {"Strategy": "Discount", "Effective Price P_s*": P_disc, "Expected Z (E[Z_s])": round(np.mean(Z_disc), 2)},
    {"Strategy": "Bundle pricing", "Effective Price P_s*": P_bund, "Expected Z (E[Z_s])": round(np.mean(Z_bund), 2)},
    {"Strategy": "BOGO", "Effective Price P_s*": P_bogo, "Expected Z (E[Z_s])": round(np.mean(Z_bogo), 2)}
])

print("=== Table 3 Baseline Strategy Performance under Stochastic Demand ===")
print(df_t2.to_string(index=False))