# -*- coding: utf-8 -*-
"""Table4.1: Sensitivity of the Theoretical Switching Threshold to Alternative Pricing Calibrations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JO3BWaY-b6fDfHNjRJ9Spxrf1_jXo2NU
"""

import pandas as pd

a = 200
b = 1
t = 3

Cw = 2
lam = 2

P_base = 100

theta_bundle = 0.10
theta_bogo = 0.20

P_bogo = 50


def calculate_delta_star(P_bundle):

    phi_bundle = (
        P_bundle + Cw + lam
    ) * (1 + theta_bundle)

    phi_bogo = (
        P_bogo + Cw + lam
    ) * (1 + theta_bogo)

    numerator = (
        a * (phi_bundle - phi_bogo)
        + b * (
            phi_bogo * P_bogo
            - phi_bundle * P_bundle
        )
    )

    denominator = (
        t * (phi_bundle - phi_bogo)
    )

    return numerator / denominator



scenarios = [

    ("Conservative Bundle",            0.80),
    ("Baseline",                       0.75),
    ("Moderate Bundle",                0.70),
    ("Aggressive Bundle",              0.65)

]


rows = []

for name, alpha in scenarios:

    P_bundle = P_base * alpha

    delta_star = calculate_delta_star(
        P_bundle
    )

    rows.append([
        name,
        alpha,
        round(P_bundle,2),
        round(delta_star,2)
    ])


df = pd.DataFrame(
    rows,
    columns=[
        "Calibration Scenario",
        "alpha",
        "P_Bundle",
        "δ_theoretical*"
    ]
)

print(df)


print("\nThreshold Range")
print(
    f"{df[r'δ_theoretical*'].min():.2f}"
    f"  to  "
    f"{df[r'δ_theoretical*'].max():.2f}"
)

df.to_excel(
    "Table_4A_Threshold_Robustness.xlsx",
    index=False
)