# -*- coding: utf-8 -*-
"""TableA2: Representative Multi-Factor Policy Scenarios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y7N6YecI8TN6DsC9PV5wiLNBICGU1T2j
"""

import numpy as np
import pandas as pd


a = 200
b = 1.0
t = 3

P_discount = 95
P_bundle = 75
P_bogo = 50

theta_discount = 0.00
theta_bundle = 0.10
theta_bogo = 0.20

C = 40
Cw = 2

sigma = 20
N = 10000



np.random.seed(42)

epsilon = np.random.normal(
    0,
    sigma,
    N
)



def evaluate(delta, lam, Q):


    D_disc = np.maximum(
        (1 + theta_discount)
        * (a - b*P_discount - delta*t)
        + epsilon,
        0
    )

    Y_disc = np.minimum(Q, D_disc)

    Z_disc = np.mean(
        P_discount*Y_disc
        - C*Q
        - (Cw + lam)*(Q - Y_disc)
    )


    D_bundle = np.maximum(
        (1 + theta_bundle)
        * (a - b*P_bundle - delta*t)
        + epsilon,
        0
    )

    Y_bundle = np.minimum(Q, D_bundle)

    Z_bundle = np.mean(
        P_bundle*Y_bundle
        - C*Q
        - (Cw + lam)*(Q - Y_bundle)
    )


    D_bogo = np.maximum(
        (1 + theta_bogo)
        * (a - b*P_bogo - delta*t)
        + epsilon,
        0
    )

    Y_bogo = np.minimum(Q, D_bogo)

    Z_bogo = np.mean(
        P_bogo*Y_bogo
        - C*Q
        - (Cw + lam)*(Q - Y_bogo)
    )

    values = {
        "Discount": Z_disc,
        "Bundle": Z_bundle,
        "BOGO": Z_bogo
    }

    optimal = max(values, key=values.get)

    return (
        round(Z_disc,2),
        round(Z_bundle,2),
        round(Z_bogo,2),
        optimal
    )


scenarios = [
    (2,2,80),
    (2,2,100),
    (2,2,150),
    (2,2,200),
    (2,2,250),
    (2,2,300),

    (2,8,200),
    (2,14,200),
    (2,20,200),

    (8,2,200),
    (12,2,200),
    (14,2,200),
    (16,2,200),
    (17,2,200),
    (18,2,200),
    (20,2,200),

    (2,20,300),
    (20,20,300),
    (20,20,200),
    (20,2,100)
]



rows = []

for delta, lam, Q in scenarios:

    Zd, Zb, Zg, opt = evaluate(
        delta,
        lam,
        Q
    )

    rows.append([
        delta,
        lam,
        Q,
        Zd,
        Zb,
        Zg,
        opt
    ])

df = pd.DataFrame(
    rows,
    columns=[
        "delta",
        "lambda",
        "Q",
        "Discount",
        "Bundle",
        "BOGO",
        "Optimal"
    ]
)

print(df)

df.to_excel(
    "Table_A2.xlsx",
    index=False
)